import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Menus from "../components/Menus";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [account, setAccount] = useState(null);
    const [metaMaskInstalled, setMetaMaskInstalled] = useState(false);
    const enableMetaMask = () => {
        const { ethereum } = window;
        //If MetaMask is installed, then we can get the accounts
        const getAccounts = async () => {
            //const accounts = await ethereum.enable();
            const accounts = await ethereum.request({
                method: "eth_requestAccounts",
            });
            setAccount(accounts[0]);
        };

        getAccounts();
    };

    useEffect(() => {
        if (typeof window !== "undefined") {
            //Have to check the ethereum binding on the window object to see if it's installed
            const { ethereum } = window;
            console.log(
                "metamask installed - ",
                Boolean(ethereum && ethereum.isMetaMask)
            );
            if (Boolean(ethereum && ethereum.isMetaMask)) {
                //const accounts = ethereum.enable();
                const getAccounts = async () => {
                    //const accounts = await ethereum.enable();
                    const accounts = await ethereum.request({
                        method: "eth_requestAccounts",
                    });
                    setAccount(accounts[0]);
                };
                getAccounts;
                setMetaMaskInstalled(true);
            } else {
                setMetaMaskInstalled(false);
            }
        }
    }, [account]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Mint Qoddi NFT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {metaMaskInstalled ? (
                    <>
                        {account && <h1 className={styles.title}>{account}</h1>}

                        <Image
                            src="https://ipfs.io/ipfs/bafkreidahjp3fnwpu2zvydvy4imm7wktwy2a4a3ypjxno3hdwn4x5iao3e"
                            width={300}
                            height="100"
                            alt="Qoddi Logo"
                        />

                        <button
                            onClick={enableMetaMask}
                            className="enableMetamask"
                        >
                            Connect To MetaMask To Mint NFT of Qoddi Logo
                        </button>
                    </>
                ) : (
                    <h3>Metamask not installed in your browser</h3>
                )}
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
