import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
    const enableMetaMask = () => {
        window.ethereum.enable();
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Connect to metamask clicking the button
                </h1>

                <button onClick={enableMetaMask} className="enableMetamask">
                    Enable MetaMAsk
                </button>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
